### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by LuongQuyTan1999** [hoapha1009/ShopeeUI#1]
Hiện tại thì file README của bạn viết chưa được ổn cho lắm, có thể tham khảo các link sau và update lại READ của bạn:
- https://github.com/nhim175/shave-it 
- https://github.com/nhim175/coders-tokyo-cli
- https://github.com/nhim175/coders-tokyo-web

Hướng dẫn viết README chuẩn:
- https://www.makeareadme.com/

**Comment by buymed-hoangpham** [comment]
. Cám ơn ad, để mình sửa lại.

Vào 14:28, Th 4, 22 thg 4, 2020 luongquytan <notifications@github.com> đã
viết:
